server:
  port: 8989  # 指定端口
  servlet:
    context-path: /ems-jsp  # 指定项目名
    jsp:
      init-parameters:
        development: true  # 开启jsp模板开发模式，更新jsp之后不需要重启

spring:
  mvc:  # 配置jsp模板
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems-jsp?serverTimeZone=GMT%2B8
    username: root
    password: lx123456

mybatis:
  mapper-locations: classpath:com/liuxiaocs/mapper/*.xml
  type-aliases-package: com.liuxiaocs.entity

# 配置日志使用
logging:
  level:
    root: info
    com.liuxiaocs: debug  # 指定包日志


