server:
  port: 8989
  servlet:
    context-path: /springboot_demo3  # 指定应用名称
# 整合mybatis相关配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootssm?serverTimeZone=GMT%2B8
    username: root
    password: lx123456
mybatis:
  mapper-locations: classpath:com/liuxiaocs/mapper/*.xml  # 指定mapper配置文件位置
  type-aliases-package: com.liuxiaocs.entity  # 指定实体类包名，默认别名：类名 类名首字母小写

